- name: Set bash path for Linux hosts
  ansible.builtin.set_fact:
    bash_path: /bin/bash
  when: ansible_os_family != 'OpenBSD'

- name: Set bash path for OpenBSD hosts
  ansible.builtin.set_fact:
    bash_path: /usr/local/bin/bash
  when: ansible_os_family == 'OpenBSD'

- name: Ensure group "wheel" exists
  ansible.builtin.group:
    name: wheel
    state: present

- name: Create the user vinishor
  ansible.builtin.user:
    name: vinishor
    home: /home/vinishor
    shell: '{{ bash_path }}'
    groups: wheel
    append: true
    state: present

- name: Set up ssh directory for vinishor
  ansible.builtin.file:
    path: /home/vinishor/.ssh
    owner: vinishor
    state: directory
    mode: 0700

- name: Add ssh keys for allowing connections
  ansible.builtin.template:
   src: authorized_keys
   dest: /home/vinishor/.ssh/authorized_keys
   owner: vinishor
   mode: 0600

- name: OpenBSD | Set up its profile file
  ansible.builtin.template:
   src: profile
   dest: /home/vinishor/.profile
   owner: vinishor
   mode: 0644
  when: ansible_os_family == 'OpenBSD'

- name: Set up its bashrc file
  ansible.builtin.template:
   src: bashrc
   dest: /home/vinishor/.bashrc
   owner: vinishor
   mode: 0644