- name: Linux | Set bash path for Linux hosts
  ansible.builtin.set_fact:
    bash_path: /bin/bash
  when: ansible_os_family != 'OpenBSD'

- name: OpenBSD | Set bash path for OpenBSD hosts
  ansible.builtin.set_fact:
    bash_path: /usr/local/bin/bash
  when: ansible_os_family == 'OpenBSD'

- name: All hosts | Ensure group "wheel" exists
  ansible.builtin.group:
    name: wheel
    state: present
  when: ansible_os_family != 'Solaris'

- name: All hosts | Create the user vinishor
  ansible.builtin.user:
    name: vinishor
    home: /home/vinishor
    shell: '{{ bash_path }}'
    groups: wheel
    append: true
    state: present
  when: ansible_os_family != 'Solaris'

- name: All hosts | Set up home directory permissions for vinishor
  ansible.builtin.file:
    path: /home/vinishor
    owner: vinishor
    state: directory
    mode: 0700

- name: All hosts | Set up ssh directory for vinishor
  ansible.builtin.file:
    path: /home/vinishor/.ssh
    owner: vinishor
    state: directory
    mode: 0700

- name: All hosts | Add ssh keys for allowing connections
  ansible.builtin.template:
   src: authorized_keys
   dest: /home/vinishor/.ssh/authorized_keys
   owner: vinishor
   mode: 0600

- name: OpenBSD | Set up its profile file
  ansible.builtin.template:
   src: profile
   dest: /home/vinishor/.profile
   owner: vinishor
   mode: 0640
  when: ansible_os_family == 'OpenBSD'

- name: All hosts | Set up its bashrc file
  ansible.builtin.template:
   src: bashrc
   dest: /home/vinishor/.bashrc
   owner: vinishor
   mode: 0640

- name: Linux | Install sudoers file for wheel group
  ansible.builtin.template:
    src: wheel
    dest: "/etc/sudoers.d/wheel"
    backup: yes
    owner: root
    group: root
    mode: 0640
    validate: /usr/sbin/visudo -cf %s
  when: ansible_os_family != 'OpenBSD' or ansible_os_family != 'Solaris'

- name: Linux | Correct sudoers file permissions for ansible user
  ansible.builtin.file:
    path: "/etc/sudoers.d/ansible"
    owner: root
    group: root
    mode: 0640
  when: ansible_os_family != 'OpenBSD' or ansible_os_family != 'Solaris'

- name: Openbsd | Configure doas
  ansible.builtin.template:
    src: doas.conf
    dest: /etc/doas.conf
    mode: 0640
    owner: root
    group: wheel
    backup: yes
  when: ansible_os_family == 'OpenBSD'
  tags: obsd-doas

- name: Linux | Define MOTD file
  ansible.builtin.shell:
    cmd: figlet -t {{ inventory_hostname_short | quote }} > /etc/motd
  when: ansible_os_family != 'OpenBSD'

- name: OpenBSD | Define MOTD file
  ansible.builtin.shell:
    cmd: head -n 2 /etc/motd > /etc/motd.new && figlet -t {{ inventory_hostname_short | quote }} >> /etc/motd.new && mv /etc/motd.new /etc/motd
  when: ansible_os_family == 'OpenBSD'
