---

- name: Fedora | install EPEL repo
  ansible.builtin.yum:
    name: 'epel-release'
    state: latest
    update_cache: yes
  when:
    - ansible_os_family == 'RedHat'
    - ansible_facts['distribution'] != "Fedora"
  tags: rh-epel

- name: Tools | install common packages for servers
  ansible.builtin.package:
    name: '{{ common_packages }}'
    state: latest
  tags: common-tools

- name: Tools | configure vi on OpenBSD hosts
  ansible.builtin.template:
   src: vi.exrc
   dest: /etc/vi.exrc
  when: ansible_os_family == 'OpenBSD'
  tags: obsd-viexrc