---

- name: RH | install EPEL repo
  ansible.builtin.yum:
    name: 'epel-release'
    state: latest
    update_cache: yes
  when:
    - ansible_os_family == 'RedHat'
    - ansible_facts['distribution'] != "Fedora"
  tags: rh-epel

- name: Common | install shared tools
  ansible.builtin.package:
    name: '{{ common_packages }}'
    state: latest
  tags: common-tools

- name: Linux | install specific tools
  ansible.builtin.package:
    name: '{{ linux_packages }}'
    state: latest
  when: ansible_os_family != 'OpenBSD'
  tags: debian-tools

- name: OpenBSD | install specific tools
  ansible.builtin.openbsd_pkg:
    name: '{{ obsd_packages }}'
    state: latest
  when: ansible_os_family == 'OpenBSD'
  tags: obsd-tools

- name: Tools | configure vi on OpenBSD hosts
  ansible.builtin.template:
   src: vi.exrc
   dest: /etc/vi.exrc
  when: ansible_os_family == 'OpenBSD'
  tags: obsd-viexrc