---

- name: Debian | install useful tools
  apt:
    name: '{{ tools_packages }}'
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'
  tags: debian-tools

- name: RH | install EPEL repo
  yum:
    name: 'epel-release'
    state: latest
    update_cache: yes
  when:
    - ansible_os_family == 'RedHat'
    - ansible_facts['distribution'] != "Fedora"
  tags: rh-epel

- name: RH | install useful tools
  yum:
    name: '{{ tools_packages }}'
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'
  tags: rh-tools

- name: OpenBSD | install useful tools
  openbsd_pkg:
    name: '{{ tools_obsd }}'
    state: latest
  when: ansible_os_family == 'OpenBSD'
  tags: obsd-tools

- name: OpenSUSE | install useful tools
  community.general.zypper:
    name: '{{ tools_packages }}'
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Suse'
  tags: osuse-tools