---

- name: Debian | install useful tools
  apt:
    pkg: '{{ tools_packages }}'
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'
  tags: debian-tools

- name: RH | install EPEL repo
  yum:
    pkg: 'epel-release'
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'
  tags: rh-epel

- name: RH | install useful tools
  yum:
    pkg: '{{ tools_packages }}'
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'
  tags: rh-tools

- name: OpenBSD | install useful tools
  openbsd_pkg:
    pkg: '{{ tools_packages }}'
    state: latest
  when: ansible_os_family == 'OpenBSD'
  tags: obsd-tools

- name: OpenSUSE | install useful tools
  community.general.zypper:
    pkg: '{{ tools_packages }}'
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Suse'
  tags: osuse-tools