---

- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: tools

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: tools

- include: openbsd.yml
  when: ansible_os_family == 'OpenBSD'
  tags: tools

- include: opensuse.yml
  when: ansible_os_family == 'Suse'
  tags: tools