---

- name: Install virtualization tools
  tags: virt-install
  ansible.builtin.package:
    name:
      - qemu-kvm
      - qemu-utils
      - qemu-system-x86
      - libvirt-daemon
    state: latest

- name: Add the user vinishor in libvirt group
  tags: virt-add-group
  ansible.builtin.user:
    name: vinishor
    groups: libvirt
    append: true

- name: Create directory for VMs storage
  tags: virt-add-vm-folder
  ansible.builtin.file:
    path: /srv/vm
    owner: libvirt-qemu
    group: libvirt-qemu
    state: directory
    mode: 0755

- name: Create directory for ISOs storage
  tags: virt-add-iso-folder
  ansible.builtin.file:
    path: /srv/iso
    owner: libvirt-qemu
    group: libvirt-qemu
    state: directory
    mode: 0755