  - job_name: "openbsd-nodes"
    static_configs:
      - targets:
        - soseki.home.arpa:9100
        - hugo.home.arpa:9100
        - eliade.home.arpa:9100
        - gemini.home.arpa:9100
        - vault.home.arpa:9100

  - job_name: "linux-nodes"
    static_configs:
      - targets:
         - palatul.home.arpa:9100
         - unbound.home.arpa:9100
         - gitea.home.arpa:9100
         - www.home.arpa:9100
         - data.home.arpa:9100
         - ansible.home.arpa:9100
         - narodnaia.home.arpa:9100
         - nas.home.arpa:9100
         - emikoussi.home.arpa:9100
         - altai.home.arpa:9100

  - job_name: "mikrotik"
    static_configs:
      - targets:
        - 10.10.99.1
        - 10.10.99.2
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116  # The SNMP exporter's real hostname:port.

  - job_name: "pve-exporter"
    static_configs:
      - targets:
         - narodnaia.home.arpa
         - emikoussi.home.arpa
         - altai.home.arpa
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9221  # PVE exporter.

  - job_name: "nginx-exporter"
    static_configs:
      - targets:
         - www.home.arpa:9113

  - job_name: "unbound-exporter"
    static_configs:
      - targets:
         - unbound.home.arpa:9167
    metrics_path: /metrics

  - job_name: "hass-exporter"
    static_configs:
      - targets:
         - 10.10.30.10:8123
    metrics_path: /api/prometheus
    scrape_interval: 60s
    scheme: http
    authorization:
      credentials: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI5MTJjYzQ5ZGM3ZTA0YzBiOWRjMDk3OGJmNTFkZGUwNSIsImlhdCI6MTcwOTU1MTc0MSwiZXhwIjoyMDI0OTExNzQxfQ.L5TN5jHCRqexhEpHystNLZNxbMMHG2S1EGjaMb_s3dU"
