  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 5s
    static_configs:
      - targets:
          - https://automario.eu
          - https://mail.automario.eu
          - https://mail2.automario.eu
          - https://unbon.cafe
          - https://avoir.unbon.cafe
          - https://automaticsappo.ro
          - https://kuma.am.gugod.fr
    relabel_configs:
       - source_labels: [__address__]
         target_label: __param_target
       - source_labels: [__param_target]
         target_label: target
       - target_label: __address__
         replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
