- name: Disable root for SSH connections
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^PermitRootLogin" 
    line: "PermitRootLogin no" 
    state: present
  notify: restart ssh

- name: Disable passwords connections with SSH
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^PasswordAuthentication" 
    line: "PasswordAuthentication no" 
    state: present
  notify: restart ssh

- name: Disable passwords connections with SSH (for OpenSUSE)
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^ChallengeResponseAuthentication" 
    line: "ChallengeResponseAuthentication no" 
    state: present
  notify: restart ssh

- name: Enable the SSH banner
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^Banner" 
    line: "Banner /etc/ssh/banner" 
    state: present
  notify: restart ssh

- name: Add a SSH banner
  template:
   src: banner
   dest: /etc/ssh/banner