- name: Enable SSH service
  ansible.builtin.service:
    name: sshd
    enabled: yes
    state: started

- name: Disable root account for SSH connections
  ansible.builtin.lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^PermitRootLogin" 
    line: "PermitRootLogin no" 
    state: present
  notify: restart ssh

- name: Disable passwords connections with SSH
  ansible.builtin.lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^PasswordAuthentication" 
    line: "PasswordAuthentication no" 
    state: present
  notify: restart ssh

- name: Disable passwords connections for PAM
  ansible.builtin.lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^ChallengeResponseAuthentication" 
    line: "ChallengeResponseAuthentication no" 
    state: present
  notify: restart ssh

- name: Enable the SSH banner
  ansible.builtin.lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^Banner" 
    line: "Banner /etc/ssh/banner" 
    state: present
  notify: restart ssh

- name: Add a SSH banner
  ansible.builtin.template:
   src: banner
   dest: /etc/ssh/banner