---
# vars file for prometheus role
prometheus_package:
  - prometheus
  - alertmanager
prometheus_service: prometheus
alertmanager_service: alertmanager
prometheus_config: '/etc/prometheus/prometheus.yml'
alertmanager_config: '/etc/alertmanager/alertmanager.yml'
alertmanager_rules: '/etc/alertmanager/rules'
