---

- name: Load package and service names
  include_vars: "{{ ansible_os_family|lower }}.yml"

- name: Debian - Add Grafana GPG key
  tags: debian-promtail-key
  when: ansible_os_family == 'Debian'
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'

- name: Debian - Add Grafana repo
  tags: debian-promtail-repo
  when: ansible_os_family == 'Debian'
  ansible.builtin.template:
   src: debian-repo
   dest: /etc/apt/sources.list.d/grafana.list

- name: Debian - Update package cache
  tags: debian-promtail-repo-update
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
   update_cache: yes

- name: Install Promtail
  tags: promtail-install
  ansible.builtin.package:
    name: '{{ promtail_package }}'
    state: latest

- name: Ensure Promtail to have the good rights for reading logs
  tags: promtail-group-logreading
  ansible.builtin.user:
    name: '{{ promtail_user }}'
    groups: '{{ promtail_group }}'
    append: true

- name: Enable Promtail configuration
  tags: promtail-configure
  ansible.builtin.template:
   src: promtail.config
   dest: '{{ promtail_config }}'
  notify: restart promtail

- name: Enable Promtail service
  tags: promtail-enable
  ansible.builtin.service:
    name: '{{ promtail_service }}'
    state: started
    enabled: yes
