---

- name: Load package and service names
  include_vars: "{{ ansible_os_family|lower }}.yml"

- name: Install Node-exporter
  tags: node-install
  ansible.builtin.package:
    name: '{{ node_package }}'
    state: latest

- name: Enable Node-exporter service
  tags: node-enable
  ansible.builtin.service:
    name: '{{ node_service }}'
    state: started
    enabled: yes
