---

- name: Install Cockpit
  tags: cockpit-install
  ansible.builtin.yum:
    pkg:
      - cockpit
      - cockpit-machines
      - cockpit-bridge
    state: latest
    update_cache: yes

- name: Enable Cockpit service
  tags: cockpit-enable
  ansible.builtin.service:
    name: cockpit.socket
    state: started
    enabled: yes