---

- name: Install Cockpit
  tags: cockpit-install
  ansible.builtin.package:
    name:
      - cockpit
      - cockpit-machines
      - cockpit-bridge
    state: latest

- name: Enable Cockpit service
  tags: cockpit-enable
  ansible.builtin.service:
    name: cockpit.socket
    state: started
    enabled: yes