---
# Playbook to set up monitoring modules

- name: Install and configure the control node
  hosts: palatul.home.arpa
  become: yes
  roles:
    - grafana
    - loki

- name: Install and configure Prometheus nodes
  hosts: monitoring
  become: yes
  roles:
    - prometheus

- name: Install and configure nodes
  hosts: all
  become: yes
  roles:
    - promtail
    - node-exporter
