---
# Playbook to set up monitoring modules

- name: Install and configure the control node
  hosts: palatul.home.arpa
  become: yes
  roles:
    - grafana

- name: Install and configure Prometheus node - Main node
  hosts: palatul.home.arpa
  become: yes
  roles:
    - prometheus
  vars:
    blackbox: false
    scrape_files:
      - /etc/prometheus/scrape-main.yml

- name: Install and configure Prometheus node - Blackbox nodes
  hosts: blackbox
  become: yes
  roles:
    - prometheus
    - blackbox-exporter
  vars:
    blackbox: true
    scrape_files:
      - /etc/prometheus/scrape-blackbox.yml

- name: Install and configure nodes - Linux
  hosts:
    - debian
    - rhel
  become: yes
  roles:
    - node-exporter

- name: Install and configure nodes - OpenBSD
  hosts:
    - openbsd
  become: yes
  become_method: doas
  roles:
    - node-exporter
