---
# Playbook to set up monitoring modules

- name: Install and configure the control node
  hosts: palatul.home.arpa
  become: yes
  roles:
    - grafana
    - loki
    - prometheus

- name: Install and configure nodes
  hosts: all
  become: yes
  roles:
    - promtail
    - node-exporter
  vars:
    - names:
        files:
          - "{{ansible_os_family | lower }}.yml"
