---
# Playbook to set up monitoring modules

- name: Install and configure the control node
  hosts: palatul.home.arpa
  become: yes
  roles:
    - grafana
    - loki

- name: Install and configure Prometheus node - Main
  hosts: palatul.home.arpa
  become: yes
  roles:
    - prometheus
  vars:
    scrape_configs:
      - /etc/prometheus/scrape-main.yml

- name: Install and configure Prometheus node - Blackbox
  hosts: soseki.home.arpa
  become: yes
  roles:
    - prometheus
  vars:
    scrape_configs:
      - /etc/prometheus/scrape-blackbox.yml

- name: Install and configure nodes
  hosts: all
  become: yes
  roles:
    - promtail
    - node-exporter
