---
# Playbook to set up the servers

- name: Configure access and install work tools
  hosts: all
  become: yes
  roles:
    - ssh
    - users
    - tools

- name: Configure Cockpit for VM management
  hosts: ansible.home.arpa
  become: yes
  roles:
    - cockpit