---
# Playbook to set up the servers

- name: Configure access and install work tools
  hosts: all
  become: yes
  roles:
    - ssh
    - tools
    - users

- name: Configure Cockpit for VM management
  hosts:
    - ansible.home.arpa
    - hypervisors
  become: yes
  roles:
    - cockpit